version: 2.1

jobs:
  deploy:
    docker:
    - image: amazon/aws-cli
    steps:
    - checkout
    - run:
        name: refresh and plan
        command: |
          terraform refresh
          terraform plan

workflows:
  deploy:
    jobs:
    - refresh and plan
