version: 2.1

jobs:
  refresh and plan:
    docker:
    - image: amazon/aws-cli
    steps:
    - checkout
    - run:
        name: Terraform refresh and plan
        command: |
          terraform refresh
          terraform plan

workflows:
  refreshplan:
    jobs:
    - refresh and plan
