version: 2.1

executors:
  docker-executor:
    machine:
      image: ubuntu-2204:current

jobs:
  build-and-push:
    executor: docker-executor
    steps:
    - checkout

    - run:
        name: Install AWS CLI
        command: |
          sudo apt-get update && sudo apt-get install -y awscli

    - run:
        name: Authenticate with AWS ECR
        command: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

    - run:
        name: Build Docker Image
        command: |
          pwd
          ls -R
          docker build -t $ECR_REPOSITORY -f current_working/tasky/Dockerfile current_working/tasky

    - run:
        name: Tag Docker Image
        command: |
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - run:
        name: Push Docker Image to AWS ECR
        command: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

workflows:
  version: 2
  build-and-push:
    jobs:
    - build-and-push
