version: 2.1

executors:
  aws-executor:
    docker:
    - image: amazon/aws-cli
    resource_class: medium

jobs:
  deploy:
    executor: aws-executor
    steps:
    - checkout

    - run:
        name: Install kubectl
        command: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mv kubectl /usr/local/bin/

    - run:
        name: Authenticate with AWS
        command: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION

    - run:
        name: Update kubeconfig for EKS
        command: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

    - run:
        name: Create ECR Pull Secret in Kubernetes
        command: |
          kubectl create secret docker-registry ecr-registry-secret \
            --docker-server=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com \
            --docker-username=AWS \
            --docker-password=$(aws ecr get-login-password --region $AWS_REGION) \
            --namespace default || true  # Ignore error if secret already exists

    - run:
        name: Deploy to Kubernetes
        command: |
          echo "
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: webapp-deployment
            labels:
              app: webapp
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: webapp
            template:
              metadata:
                labels:
                  app: webapp
              spec:
                containers:
                - name: tasky
                  image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/lone_klughardt:latest
                  ports:
                  - containerPort: 8080
                  env:
                  - name: MONGODB_URI
                    valueFrom:
                      secretKeyRef:
                        name: mongodb-secret
                        key: MONGO_URI
                imagePullSecrets:
                  - name: ecr-registry-secret
          " | kubectl apply -f -

workflows:
  version: 2
  deploy:
    jobs:
    - deploy
