version: 2.1

jobs:
  deploy:
    docker:
    - image: hashicorp/terraform:light
    steps:
    - checkout
    - run:
        name: refresh and plan
        command: |
          terraform init
          terraform refresh
          terraform plan

workflows:
  deploy:
    jobs:
    - refresh and plan
